"""Generate evidence.json and EVIDENCE.md: the actual verse text, from this
repository, for every witness of every case in mistranslations.json.

The dataset asserts that a rendering shifted. This script makes the assertion
checkable by quoting the texts side by side, straight out of versions/.
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from bible import Bible, Ref  # noqa: E402

HERE = os.path.dirname(__file__)
DATASET = os.path.join(HERE, "..", "mistranslations.json")
OUT_JSON = os.path.join(HERE, "..", "evidence.json")
OUT_MD = os.path.join(HERE, "..", "EVIDENCE.md")

SIDE_LABEL = {
    "source": "Source-language reading",
    "shifted": "Shifted rendering",
    "corrected": "Reading that restores the source",
}


def build() -> dict:
    data = json.load(open(DATASET, encoding="utf-8"))
    bible = Bible()
    out = {
        "generated_from": "mistranslations.json",
        "schema_version": data["schema_version"],
        "note": "Verse text quoted verbatim from this repository's version files. "
                "Regenerate with tools/build_evidence.py after editing the dataset.",
        "cases": [],
    }
    for case in data["cases"]:
        refs = [Ref.parse(r) for r in case["references"]]
        entry = {
            "id": case["id"],
            "title": case["title"],
            "type": case["type"],
            "consensus": case["consensus"],
            "references": case["references"],
            "readings": {},
        }
        for side, keys in case["witnesses"].items():
            rows = []
            for version_key in keys:
                quotes = {}
                for ref in refs:
                    text = bible.try_verse(version_key, ref)
                    if text is not None:
                        quotes[str(ref)] = text
                if quotes:
                    rows.append({"version": version_key, "text": quotes})
            entry["readings"][side] = rows
        out["cases"].append(entry)
    return out


def render_markdown(evidence: dict) -> str:
    lines = [
        "# Evidence",
        "",
        "Generated by `tools/build_evidence.py`. Every line below is quoted verbatim",
        "from a version file in this repository - nothing here is written by hand.",
        "",
    ]
    for case in evidence["cases"]:
        lines.append(f"## {case['title']}")
        lines.append("")
        lines.append(f"`{case['id']}` &middot; *{case['type']}* &middot; consensus: **{case['consensus']}**  ")
        lines.append(f"References: {', '.join(case['references'])}")
        lines.append("")
        for side in ("source", "shifted", "corrected"):
            rows = case["readings"].get(side, [])
            lines.append(f"**{SIDE_LABEL[side]}**")
            lines.append("")
            if not rows:
                lines.append("_No witness in this repository._")
                lines.append("")
                continue
            for row in rows:
                for ref, text in row["text"].items():
                    lines.append(f"- `{row['version']}` — {ref} — {text}")
            lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    evidence = build()
    with open(OUT_JSON, "w", encoding="utf-8") as fh:
        json.dump(evidence, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    with open(OUT_MD, "w", encoding="utf-8") as fh:
        fh.write(render_markdown(evidence))
    quotes = sum(
        len(row["text"])
        for case in evidence["cases"]
        for rows in case["readings"].values()
        for row in rows
    )
    print(f"wrote evidence.json and EVIDENCE.md: {len(evidence['cases'])} cases, {quotes} quoted verses")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
