"""Validate beliefs.json and run its machine-checkable claims against the corpus.

This dataset's distinctive move is that many of its claims are *absence* claims -
"this phrase is in no English Bible", "this Hebrew word never occurs in Genesis" -
and absence is exactly what a 142-version corpus can establish mechanically.

Two check kinds, declared per case in a `verified` block:

  phrase          a regex over version texts, with the number of versions it may
                  appear in. expect_versions: 0 proves the phrase is absent.
  strongs_absent  a Strong's number must not occur in the named book(s).

A case with no `verified` block is a historical claim carrying citations instead;
those are flagged in the summary so the ratio stays visible.

Exit status is non-zero on any failure, so this works as a CI gate.
"""

from __future__ import annotations

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(REPO, "research", "mistranslations", "tools"))
sys.path.insert(0, os.path.join(REPO, "tools"))
from bible import Bible, Ref  # noqa: E402
from lexicon import Lexicon  # noqa: E402

DATASET = os.path.join(HERE, "..", "beliefs.json")
REPORT = os.path.join(HERE, "..", "ABSENCE.md")
SUPPORT = os.path.join(HERE, "..", "SUPPORT.md")

REQUIRED = ["id", "title", "type", "consensus", "claim", "what_the_text_says",
            "what_it_rests_on", "origin", "held_by", "caveat", "sources",
            "conceptual_support"]

QUOTE_FROM = ["en/NEW REVISED STANDARD VERSION", "en/KING JAMES BIBLE",
              "apocrypha/NEW REVISED STANDARD VERSION"]


def quote(bible, raw):
    """Return (version_key, text) for a reference, trying the canon then the deuterocanon."""
    for key in QUOTE_FROM:
        if key in bible.versions:
            text = bible.try_verse(key, raw)
            if text:
                return key, text
    return None, None


def english_versions(bible: Bible) -> list[str]:
    return sorted(k for k in bible.versions if k.startswith("en/"))


def run_phrase(bible: Bible, spec: dict) -> dict:
    rx = re.compile(spec["pattern"], re.IGNORECASE)
    scope = spec.get("scope", "english")
    keys = english_versions(bible) if scope == "english" else sorted(bible.versions)
    books = spec.get("books")
    only_ch = {str(c) for c in spec.get("chapters", [])}
    hit_versions, samples = set(), []
    for key in keys:
        data = bible._load(key)
        for book, chapters in data.items():
            if books and book not in books:
                continue
            for chapter, verses in chapters.items():
                if only_ch and str(chapter) not in only_ch:
                    continue
                for verse, text in verses.items():
                    if rx.search(text):
                        hit_versions.add(key)
                        if len(samples) < 3:
                            samples.append((key, f"{book} {chapter}:{verse}", text[:110]))
    return {"searched": len(keys), "hit_versions": len(hit_versions), "samples": samples}


def run_strongs(lex: Lexicon, spec: dict) -> dict:
    refs = lex.occurrences(spec["strongs"])
    books = set(spec["absent_from"])
    offending = [r for r in refs if r.rsplit(" ", 1)[0] in books]
    return {"total_occurrences": len(refs), "in_named_books": len(offending),
            "elsewhere": refs[:6]}


def main() -> int:
    data = json.load(open(DATASET, encoding="utf-8"))
    bible, lex = Bible(), Lexicon()
    errors, warnings, unanswered = [], [], []
    quoted = 0
    replies = 0
    VERDICTS = set(data["support_verdicts"])
    types, levels = set(data["taxonomy"]), set(data["consensus_levels"])
    checked = 0
    lines = ["# Verified absences", "",
             "Generated by `tools/verify.py`. Each row is a claim this corpus can settle",
             "mechanically — a phrase that appears in no Bible, or a word that never occurs",
             "in the book people place it in. Nothing here is asserted by hand.", "",
             "| Case | Check | Result |", "| --- | --- | --- |"]

    seen = set()
    for case in data["cases"]:
        cid = case.get("id", "<no id>")
        for field in REQUIRED:
            if field == "caveat":
                if field not in case:
                    errors.append(f"{cid}: missing field 'caveat' (use null to say none applies)")
                continue
            if field == "sources" and case.get("scholarship"):
                continue
            if not case.get(field):
                errors.append(f"{cid}: missing or empty field {field!r}")
        if cid in seen:
            errors.append(f"{cid}: duplicate id")
        seen.add(cid)
        if case.get("type") not in types:
            errors.append(f"{cid}: unknown type {case.get('type')!r}")
        if case.get("consensus") not in levels:
            errors.append(f"{cid}: unknown consensus {case.get('consensus')!r}")

        # Scripture references cited in what_the_text_says must resolve.
        for raw in case.get("references", []):
            try:
                ref = Ref.parse(raw)
            except ValueError as exc:
                errors.append(f"{cid}: {exc}")
                continue
            if not bible.has("en/NEW REVISED STANDARD VERSION", ref) and \
               not bible.has("en/KING JAMES BIBLE", ref):
                errors.append(f"{cid}: reference {raw!r} does not resolve")

        support = case.get("conceptual_support") or {}
        verdict = support.get("verdict")
        if verdict not in VERDICTS:
            errors.append(f"{cid}: conceptual_support.verdict {verdict!r} not one of {sorted(VERDICTS)}")
        if not support.get("summary"):
            errors.append(f"{cid}: conceptual_support has no summary")
        passages = support.get("passages") or []
        if not passages:
            errors.append(f"{cid}: conceptual_support cites no passages - "
                          "an empty audit is a claim too, and must be made explicitly")
        for entry in passages:
            if entry.get("direction") not in ("for", "against"):
                errors.append(f"{cid}: passage {entry.get('ref')!r} has no for/against direction")
            if not entry.get("why"):
                errors.append(f"{cid}: passage {entry.get('ref')!r} has no reason given")
            if entry.get("direction") == "against":
                if entry.get("reply"):
                    replies += 1
                elif case.get("type") == "later-doctrine":
                    unanswered.append(
                        f"{cid}: objection {entry.get('ref')!r} carries no reply, and this is a "
                        "later-doctrine case - an objection printed without the tradition's answer "
                        "reads as a refutation")
            key, text = quote(bible, entry.get("ref", ""))
            if text is None:
                errors.append(f"{cid}: support passage {entry.get('ref')!r} does not resolve")
            else:
                entry["_quoted_from"] = key
                entry["_text"] = text
                quoted += 1
        if verdict == "none" and any(e.get("direction") == "for" for e in passages):
            errors.append(f"{cid}: verdict 'none' but a supporting passage is cited")

        spec = case.get("verified")
        if not spec:
            warnings.append(f"{cid}: historical claim, no lexical check")
            continue
        checked += 1
        if spec["kind"] == "phrase":
            res = run_phrase(bible, spec)
            allowed = spec.get("expect_versions", 0)
            ok = res["hit_versions"] <= allowed
            detail = (f"appears in **{res['hit_versions']} of {res['searched']}** "
                      f"English versions (allowed {allowed})")
            if not ok:
                errors.append(f"{cid}: phrase found in {res['hit_versions']} versions, "
                              f"expected at most {allowed}; e.g. {res['samples'][:1]}")
            lines.append(f"| `{cid}` | phrase `{spec['pattern']}` | {detail} |")
        elif spec["kind"] == "strongs_absent":
            res = run_strongs(lex, spec)
            ok = res["in_named_books"] == 0
            where = ", ".join(spec["absent_from"])
            detail = (f"`{spec['strongs']}` occurs **{res['total_occurrences']}×**, "
                      f"**{res['in_named_books']}×** in {where}")
            if not ok:
                errors.append(f"{cid}: {spec['strongs']} occurs in {where}")
            lines.append(f"| `{cid}` | Strong's `{spec['strongs']}` absent from {where} | {detail} |")
        else:
            errors.append(f"{cid}: unknown check kind {spec['kind']!r}")

    lines += ["", f"**{checked} of {len(data['cases'])} cases carry a lexical check.** "
                  "The rest are historical claims, carried by citation instead.", "",
              "A lexical result on its own proves only that a *wording* is absent. "
              "See [`SUPPORT.md`](SUPPORT.md) for whether the *idea* is derivable from the text."]
    with open(REPORT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    tally = {}
    for case in data["cases"]:
        v = (case.get("conceptual_support") or {}).get("verdict", "?")
        tally[v] = tally.get(v, 0) + 1
    sup = ["# Conceptual support", "",
           "Could someone arrive at this belief from the Bible without ever seeing the phrase?",
           "",
           "A regex proves a wording is absent. It says nothing about whether the idea is there.",
           "This report is the other half: for every case, the passages a reasonable reader could",
           "build the belief from, and the passages that cut against it. Every verse is resolved and",
           "quoted by `tools/verify.py` — the **quotations are mechanical, the gradings are judgement**,",
           "and they are kept visibly separate.", "",
           "Where a passage cuts **against** a belief and the tradition holding it has a standard answer,",
           "that answer is printed beneath the objection. Without it this file would be a one-sided brief:",
           "an objection presented as though it were a refutation.", "",
           "| Verdict | Cases | Meaning |", "| --- | ---: | --- |"]
    for v, meaning in data["support_verdicts"].items():
        sup.append(f"| `{v}` | {tally.get(v, 0)} | {meaning} |")
    sup += ["", f"**{quoted} passages resolved and quoted across {len(data['cases'])} cases; "
                f"{replies} objections carry the tradition's reply.**", ""]
    for case in data["cases"]:
        s_ = case["conceptual_support"]
        sup += [f"## {case['title']}", "",
                f"`{case['id']}` &middot; verdict: **{s_['verdict']}**", "",
                s_["summary"], ""]
        for entry in s_["passages"]:
            arrow = "**supports**" if entry["direction"] == "for" else "**against**"
            sup.append(f"- {arrow} &nbsp; `{entry['ref']}` — {entry['why']}  ")
            sup.append(f"  > {entry.get('_text', '')}")
            if entry.get("reply"):
                sup.append(f"  <br>↳ *Reply:* {entry['reply']}")
        sup += ["", "---", ""]
    with open(SUPPORT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(sup) + "\n")

    print(f"cases:            {len(data['cases'])}")
    print(f"lexical checks:   {checked:>4}")
    print(f"support passages: {quoted:>4} resolved and quoted")
    print(f"objections w/reply:{replies:>4}")
    print("verdicts:         " + ", ".join(f"{k} {v}" for k, v in sorted(tally.items())))
    print(f"historical only:  {len(warnings):>4}")
    print(f"unanswered objs:  {len(unanswered):>4}")
    print(f"errors:           {len(errors):>4}")
    if unanswered:
        print("\n-- doctrinal objections with no reply recorded --")
        for u in unanswered:
            print("  " + u)
    if errors:
        print("\n-- errors --")
        for e in errors:
            print("  " + e)
        return 1
    print("\nOK: every mechanical claim holds against the corpus.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
