"""Validate beliefs.json and run its machine-checkable claims against the corpus.

This dataset's distinctive move is that many of its claims are *absence* claims -
"this phrase is in no English Bible", "this Hebrew word never occurs in Genesis" -
and absence is exactly what a 142-version corpus can establish mechanically.

Two check kinds, declared per case in a `verified` block:

  phrase          a regex over version texts, with the number of versions it may
                  appear in. expect_versions: 0 proves the phrase is absent.
  strongs_absent  a Strong's number must not occur in the named book(s).

A case with no `verified` block is a historical claim carrying citations instead;
those are flagged in the summary so the ratio stays visible.

Exit status is non-zero on any failure, so this works as a CI gate.
"""

from __future__ import annotations

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(REPO, "research", "mistranslations", "tools"))
sys.path.insert(0, os.path.join(REPO, "tools"))
from bible import Bible, Ref  # noqa: E402
from lexicon import Lexicon  # noqa: E402

DATASET = os.path.join(HERE, "..", "beliefs.json")
REPORT = os.path.join(HERE, "..", "ABSENCE.md")

REQUIRED = ["id", "title", "type", "consensus", "claim", "what_the_text_says",
            "what_it_rests_on", "origin", "held_by", "caveat", "sources"]


def english_versions(bible: Bible) -> list[str]:
    return sorted(k for k in bible.versions if k.startswith("en/"))


def run_phrase(bible: Bible, spec: dict) -> dict:
    rx = re.compile(spec["pattern"], re.IGNORECASE)
    scope = spec.get("scope", "english")
    keys = english_versions(bible) if scope == "english" else sorted(bible.versions)
    books = spec.get("books")
    only_ch = {str(c) for c in spec.get("chapters", [])}
    hit_versions, samples = set(), []
    for key in keys:
        data = bible._load(key)
        for book, chapters in data.items():
            if books and book not in books:
                continue
            for chapter, verses in chapters.items():
                if only_ch and str(chapter) not in only_ch:
                    continue
                for verse, text in verses.items():
                    if rx.search(text):
                        hit_versions.add(key)
                        if len(samples) < 3:
                            samples.append((key, f"{book} {chapter}:{verse}", text[:110]))
    return {"searched": len(keys), "hit_versions": len(hit_versions), "samples": samples}


def run_strongs(lex: Lexicon, spec: dict) -> dict:
    refs = lex.occurrences(spec["strongs"])
    books = set(spec["absent_from"])
    offending = [r for r in refs if r.rsplit(" ", 1)[0] in books]
    return {"total_occurrences": len(refs), "in_named_books": len(offending),
            "elsewhere": refs[:6]}


def main() -> int:
    data = json.load(open(DATASET, encoding="utf-8"))
    bible, lex = Bible(), Lexicon()
    errors, warnings = [], []
    types, levels = set(data["taxonomy"]), set(data["consensus_levels"])
    checked = 0
    lines = ["# Verified absences", "",
             "Generated by `tools/verify.py`. Each row is a claim this corpus can settle",
             "mechanically — a phrase that appears in no Bible, or a word that never occurs",
             "in the book people place it in. Nothing here is asserted by hand.", "",
             "| Case | Check | Result |", "| --- | --- | --- |"]

    seen = set()
    for case in data["cases"]:
        cid = case.get("id", "<no id>")
        for field in REQUIRED:
            if field == "caveat":
                if field not in case:
                    errors.append(f"{cid}: missing field 'caveat' (use null to say none applies)")
                continue
            if not case.get(field):
                errors.append(f"{cid}: missing or empty field {field!r}")
        if cid in seen:
            errors.append(f"{cid}: duplicate id")
        seen.add(cid)
        if case.get("type") not in types:
            errors.append(f"{cid}: unknown type {case.get('type')!r}")
        if case.get("consensus") not in levels:
            errors.append(f"{cid}: unknown consensus {case.get('consensus')!r}")

        # Scripture references cited in what_the_text_says must resolve.
        for raw in case.get("references", []):
            try:
                ref = Ref.parse(raw)
            except ValueError as exc:
                errors.append(f"{cid}: {exc}")
                continue
            if not bible.has("en/NEW REVISED STANDARD VERSION", ref) and \
               not bible.has("en/KING JAMES BIBLE", ref):
                errors.append(f"{cid}: reference {raw!r} does not resolve")

        spec = case.get("verified")
        if not spec:
            warnings.append(f"{cid}: historical claim, no mechanical check")
            continue
        checked += 1
        if spec["kind"] == "phrase":
            res = run_phrase(bible, spec)
            allowed = spec.get("expect_versions", 0)
            ok = res["hit_versions"] <= allowed
            detail = (f"appears in **{res['hit_versions']} of {res['searched']}** "
                      f"English versions (allowed {allowed})")
            if not ok:
                errors.append(f"{cid}: phrase found in {res['hit_versions']} versions, "
                              f"expected at most {allowed}; e.g. {res['samples'][:1]}")
            lines.append(f"| `{cid}` | phrase `{spec['pattern']}` | {detail} |")
        elif spec["kind"] == "strongs_absent":
            res = run_strongs(lex, spec)
            ok = res["in_named_books"] == 0
            where = ", ".join(spec["absent_from"])
            detail = (f"`{spec['strongs']}` occurs **{res['total_occurrences']}×**, "
                      f"**{res['in_named_books']}×** in {where}")
            if not ok:
                errors.append(f"{cid}: {spec['strongs']} occurs in {where}")
            lines.append(f"| `{cid}` | Strong's `{spec['strongs']}` absent from {where} | {detail} |")
        else:
            errors.append(f"{cid}: unknown check kind {spec['kind']!r}")

    lines += ["", f"**{checked} of {len(data['cases'])} cases carry a mechanical check.** "
                  "The rest are historical claims, carried by citation instead."]
    with open(REPORT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"cases:            {len(data['cases'])}")
    print(f"mechanical checks:{checked:>4}")
    print(f"historical only:  {len(warnings):>4}")
    print(f"errors:           {len(errors):>4}")
    if errors:
        print("\n-- errors --")
        for e in errors:
            print("  " + e)
        return 1
    print("\nOK: every mechanical claim holds against the corpus.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
